### ISSUE TITLE
ePubCheck-Warning Message: CharisSILB, CharisSILBIm, CharisSILI and CharisSILR Fonts

### ISSUE THREAD

**Issue by Sudhakar2007** [IDPF/epub3-samples#18]
Dear All,

I am getting warning message while using the Charis fonts. Can I remove these fonts from the ePub. This will have an impact in the quality of rendering of contents in readers?

Is there any vital reason for using these Charis fonts in the ePub?

Thanks,
Sudhakar

**Comment by mattgarrish** [comment]
I searched the source files but can't find any instances of a Charis font in the samples, so it's not possible to offer you any advice.

I'm going to close this issue, but you can re-open if you can point to the example you're having problems with. Otherwise, I can only suggest to find a more appropriate help forum for your questions.
